# Generated by Django 4.0.4 on 2022-05-05 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_note_author_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
        migrations.AlterField(
            model_name='comment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.note'),
        ),
    ]
