# Generated by Django 4.0.4 on 2022-05-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_note_options_remove_comment_date_add_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.IntegerField()),
                ('field_2', models.IntegerField()),
            ],
            options={
                'unique_together': {('field_1', 'field_2')},
            },
        ),
    ]
