# Generated by Django 4.0.4 on 2022-05-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
